name: barcelona
favicon: null
layout_spectrum: 0.3780059046112001
typography_spectrum: 0.22893223958089948
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6688465552870184
  lightness: 0.22114803362637758
  saturation: 0.43971387622877955
  rhythmicContrast: 0.07765603763982654
purpose: []
